SELECT T2.ANIMAL_ID, T2.NAME
FROM ANIMAL_INS T1 JOIN ANIMAL_OUTS T2
ON T1.ANIMAL_ID = T2.ANIMAL_ID
WHERE (T2.ANIMAL_ID, DATEDIFF(T2.DATETIME+1, T1.DATETIME)) IN (
                    SELECT T2.ANIMAL_ID, DATEDIFF(T2.DATETIME+1, T1.DATETIME)
                    FROM ANIMAL_INS T1 JOIN ANIMAL_OUTS T2 
                    ON T1.ANIMAL_ID = T2.ANIMAL_ID
                    ORDER BY 2 DESC
                    ) 
ORDER BY DATEDIFF(T2.DATETIME+1, T1.DATETIME) DESC
LIMIT 2