-- 코드를 입력하세요
SELECT A.REST_ID AS REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO A INNER JOIN REST_REVIEW B
ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS 
HAVING ADDRESS LIKE '서울%'
ORDER BY 6 DESC, 4 DESC
