# SELECT T1.CATEGORY, COUNT(*) AS TOTAL_SALES
#     FROM BOOK T1, BOOK_SALES T2
#     WHERE T1.BOOK_ID = T2.BOOK_ID AND T2.PUBLISHED_DATE LIKE '2022-01%'
#     GROUP BY T1.CATEGORY
    
SELECT T1.CATEGORY, SUM(T2.SALES) AS TOTAL_SALES
    FROM BOOK T1, BOOK_SALES T2
    WHERE T1.BOOK_ID = T2.BOOK_ID AND T2.SALES_DATE LIKE '2022-01%'
    GROUP BY T1.CATEGORY
    ORDER BY T1.CATEGORY