# SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
# FROM FOOD_PRODUCT
# WHERE PRICE = (WHERE MAX(PRICE) FROM FOOD_PRODUCT)

SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
ORDER BY 5 DESC
LIMIT 1