-- 코드를 작성해주세요
SELECT B.ITEM_ID AS ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO A INNER JOIN (
    SELECT B.ITEM_ID AS ITEM_ID
    FROM ITEM_INFO A, ITEM_TREE B
    WHERE RARITY = 'RARE'
        AND A.ITEM_ID = PARENT_ITEM_ID
) B
ON A.ITEM_ID = B.ITEM_ID
ORDER BY 1 DESC