SELECT T3.APNT_NO, T1.PT_NAME, T1.PT_NO, T3.MCDP_CD, T2.DR_NAME, T3.APNT_YMD
FROM PATIENT T1, DOCTOR T2, APPOINTMENT T3
WHERE T1.PT_NO = T3.PT_NO 
    AND T2.DR_ID = T3.MDDR_ID
    AND T3.APNT_CNCL_YN = 'N'
    AND T3.MCDP_CD = 'CS'
    AND T3.APNT_YMD LIKE '2022-04-13%'
ORDER BY T3.APNT_YMD