SELECT A.TITLE AS TITLE, 
    A.BOARD_ID AS BOARD_ID, 
    B.REPLY_ID AS REPLY_ID, 
    B.WRITER_ID AS WRITER_ID, 
    B.CONTENTS AS CONTENTS, 
    DATE_FORMAT(B.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD A JOIN USED_GOODS_REPLY B
WHERE A.BOARD_ID = B.BOARD_ID AND A.CREATED_DATE LIKE "2022-10%"
ORDER BY 6, 1