SELECT CAR_TYPE, COUNT(*) AS CARS
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE OPTIONS LIKE '%통풍%' 
        OR OPTIONS LIKE '%열선%'
        OR OPTIONS LIKE '%가죽%'
    GROUP BY CAR_TYPE
    ORDER BY CAR_TYPE